version: "3"

services:
  application:
    build: 
      context: ./docker/php73
    container_name: 'project-php73'
    restart: 'always'
    ports:
      - "127.0.0.1:8001:80"
      - "127.0.0.1:4001:443"
    links: 
      - database
    volumes: 
      - ./public:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2

  database:
    build:
      context: "./docker/mariadb"
    container_name: 'project-db-mariadb'
    restart: 'always'
    ports:
      - "127.0.0.1:3001:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'project-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

    ports:
      - '127.0.0.1:9001:80'
    volumes: 
      - /sessions
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
      
